public class ExceptionHandling {
public static void main(String[] args) {
try {

int[] array = new int[5];
System.out.println("Array length: " + array.length);
System.out.println("Accessing element at index 10:");
System.out.println(array[10]);
int divideByZero = 10 / 0;
} catch (ArrayIndexOutOfBoundsException e) {

System.out.println("Caught ArrayIndexOutOfBoundsException: " + e.getMessage());
} catch (ArithmeticException e) {
System.out.println("Caught ArithmeticException: " + e.getMessage());
} catch (Exception e) {
System.out.println("Caught Exception: " + e.getMessage());
} finally {

System.out.println("Finally block executed.");
}
}
}
